### ISSUE TITLE
support for side_effect predicate

### ISSUE THREAD

**Issue by vdancik** [biolink/biolink-model#1051]
**Is your feature request related to a problem? Please describe.**
@tsodeinde is helping us to incorporate a database of side effects (SIDER) into MolePro. In the Biolink there is a `causes adverse event` predicate but we feel it is too strong of a statement.

**Describe the solution you'd like**
We are proposing a new predicate `has side effect` (and it's inverse, `is side effect of`) that would be sandwiched between `causes` and `causes adverse event`.

**What working group (or team) did this request originate from?**
MolePro

Note: This is relevant for members of NCATS Translator.

**Additional context**

**Tag relevant members for discussion**
@sierra-moxon @mbrush @mikebada

**Comment by sierra-moxon** [comment]
Talking to @vdancik - here is a proposal:

1) remove 'causes adverse event'
2) add 'has side effect' and 'is side effect of'
- node_aspect_qualifier (in Drug->SideEffect Association) would be used to specify "positive" or "negative" side effects as well as the enumerated FDA "IND (investigational new drug) safety reporting qualification" guidelines: https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfcfr/cfrsearch.cfm?fr=312.32 .

**Comment by andrewsu** [comment]
Subscribing to this issue because mychem has ingested sider data.  For example, see http://mychem.info/v1/query?q=_exists_:sider&fields=sider for the (currently) 1507 records with sider data.  However, we do not yet include this info in our [OpenAPI / SmartAPI record](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mychem.info/openapi_full.yml) at least in part due to data modeling issues, as mentioned in [this comment](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mychem.info/openapi_full.yml#L521).
