### ISSUE TITLE
contraindicated

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#110]
Drugs can be contraindicated for a condition.  Drugcentral has this kind of information (from mychem.info):

```
"contraindication": [
        {
          "concept_name": "Gastrointestinal hypomotility",
          "cui_semantic_type": "T047",
          "snomed_concept_id": 421807004,
          "snomed_full_name": "Gastrointestinal hypomotility",
          "umls_cui": "C0948779"
        },
```

Is there a good biolink-model predicate for this relationship?

**Comment by cmungall** [comment]
I would opt for generalizing somewhat such that it is free of any aspect of regulatory authorities, and modeling biologically in terms of regulating/downregulating a disease/feature

**Comment by cbizon** [comment]
That's an interesting point.   Two questions:
1) We don't really know why the drug was contraindicated, so is there a valid way to make an inference here?
2) Isn't there value in keeping the process/regulatory information?

**Comment by mbrush** [comment]
A quick search of existing ontologies and didn’t find much of use here (for a regulatory or biological interpretation).   RO has RO:0003309 (exacerbates_condition) seems close. But to Chris B's point, we may not know the reason a drug is contraindicated for a disease - it may be because it exacerbates the indicated condition, or because it causes side-effects distinct from the primary condition.  

I agree that while we would like to understand and frame contraindication in biological terms, this is often just a regulatory authority-provided relationship where the underlying biological reason for contraindication may not be known, and/or may be different across pairs of drugs and their contraindicated diseases.  

Chris M - perhaps this means that we wouldn’t want such a relation in RO, which is about biological relationships, but we can try to find another ontology/vocab to host it?  NCIt seems a good fit, but not sure they are interested in adding such a term to their carefully-defined set of properties.
 
In the short term, should I add  'contraindicated for' the biolink-model yaml and keep without a mapping?  Or do you want to further explore the idea of casting in biological terms still @cmungall?

**Comment by nlharris** [comment]
Does @cmungall still need to weigh in on this?

**Comment by deepakunni3** [comment]
Not sure what the conclusion was, but we do have `contraindicated for` in the model: https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L1822

**Comment by nlharris** [comment]
@cbizon is your need addressed?

**Comment by cbizon** [comment]
Yep, I think so thanks.
