### ISSUE TITLE
Entities in SRI

### ISSUE THREAD

**Issue by sz539** [biolink/biolink-model#1131]
We at Explanatory Agent group have detected some entities that should not be in the SRI. We used the lists of known entities and matched all items in the database against them using NLP. Additionally, we checked if the classification of entities matched a definition from WordNet (to see if something is classified as a chemical). So, everything that didn't match in this process was considered "a bad entity". The so called bad entities have been classified in two groups as the linguistic and non-linguistic groups. The entities such as "tapas", "man", "septum" or "plzf+" and "j_{q}".

Additionally, there are some ambiguous items, such as '"cat" used as a synonym for category in the context. There are also many cases that a word by itself is clearly not a medical term, but can be used as one in specific context and vice versa such as "mexican".

@sierra-moxon , please find attached two lists of the bad entities.
[linguistic.txt](https://github.com/biolink/biolink-model/files/9873373/linguistic.txt)
[non-linguistic.txt](https://github.com/biolink/biolink-model/files/9873374/non-linguistic.txt)

**Comment by nlharris** [comment]
I don't see a label for Explanatory Agent (this is different from Exploring Agent, right?)? Is it an ARA? A WG?

**Comment by sierra-moxon** [comment]
> I don't see a label for Explanatory Agent (this is different from Exploring Agent, right?)? Is it an ARA? A WG?

Yes, I think it is an ARA and different from Exploring Agent.  I went ahead and made a label.

**Comment by sierra-moxon** [comment]
@sz539 - can you please help me understand the data source you are analyzing when you say "SRI"?   Are you downloading and using the [SRI Reference KG](https://data.monarchinitiative.org/monarch-kg-dev/latest/monarch-kg.tar.gz), or are you talking about the results that are mapped via the Node Normalizer in a wider survey of all the resources in Translator (for example, I've noticed that the autocomplete used by the UI returns many more options than are currently instantiated in Translator data).  

These terms will be very helpful, I am trying to figure out the right combination of people and groups to involve here.  :)  
@kevinschaper @cbizon

**Comment by sz539** [comment]
I believe they are from Node Normalizer.

**Comment by gaurav** [comment]
Hi @sz539! Thanks for reporting this issue. There are two relevant SRI tools that you might be referring to:
* The Name Resolver ([dev](https://name-resolution-sri.renci.org/docs), [prod](https://name-lookup.transltr.io/docs)) takes a string and returns a list of identifiers that match that label. However, I can't find your exact string "j_{q}" on either the development ([results](https://name-resolution-sri.renci.org/lookup?string=j_%7Bq%7D&offset=0&limit=1000)) or production ([results](https://name-lookup.transltr.io/lookup?string=j_%7Bq%7D&offset=0&limit=1000)) version of this tool: instead, we get back names like "JQ1", "(+)-JQ1 compound", "(R)-JQ1 Acid", "JQ-1 carboxylic acid", and so on.
* The Node Normalizer ([dev](https://nodenormalization-sri.renci.org/1.3/docs), [prod](https://nodenorm.transltr.io/1.3/docs)) strictly normalizes identifiers: if you give it an identifier (like PUBCHEM.COMPOUND:46907787), it will return a list of all the identifiers and labels it considers to be identical to that one.

I'm particularly interested in the non-linguistic strings like "length (i + 1", which should never be showing up as a concept label! So I'd love to know where you found that.

Thanks again for the bug report and for your help in figuring out what's going wrong here!

**Comment by sierra-moxon** [comment]
The process by which Explanatory Agent finds these results are roughly as follows:
- Do some natural entity recognition on some text to identify entities.
- Look up entities identified by NER in the SRI Name Resolver service (https://github.com/TranslatorSRI/NameResolution, https://smart-api.info/ui/9995fed757acd034ef099dbb483c4c82#/lookup/lookup_curies_lookup_post)
  - if the service returns any identifiers that "match":
    - take the returned identifiers and pass them through the SRI Node Normalizer (https://github.com/TranslatorSRI/NodeNormalization, https://smart-api.info/ui/400f7c11028ff36f460af4ea85dc72f5#/default/get_normalized_node_handler_get_normalized_nodes_get) to return Biolink entity types.

We identified a couple of assumptions in this path that contribute to these results:
1) the results from Name Resolution Service are tuned to return as many matches as possible using a variety of vocabularies (ontologies, UMLS entries, etc. as well as their synonyms and cross-references).  The Name Resolution service also makes the decision to remove punctuation during a match so that non-standardized text will be matched, for example:
a search for "man" will return all variants of "manic" (see below). 
```
    "Manic-Depressive Psychoses",
    "Manic depressive psychosis",
    "manic-depressive disorders",
    "Manic-depressive psychosis",
```
2) The Explanatory agent definition of "match" that they hope to get from `NameResolution` services desires to be more "exact."  Currently, on a match of any kind, the Explanatory agent tool accepts any match as "exact" and then asks `NodeNormalizer` to return Biolink types.  Further, it assumes that any return from `NodeNormalizer` means that there are valid Biolink types for substrings in the match.  The granularity of matches returned is the starting point here: if the Explanatory agent would like a more stringent match, they could process the match results from the `NameResolution` service to (for example), remove non-exact matches, or respect "spaces" as breakpoints for words, or add back in punctuation, etc.  This would involve further processing the list of "matches" that return for each CURIE in this endpoint: https://smart-api.info/ui/9995fed757acd034ef099dbb483c4c82#/lookup/lookup_curies_lookup_post. 

3) We identified that NodeNormalizer types include all parent classes of that category/class/type in Biolink.  Therefore, a match to a Biolink "Small Molecule" will also be a match to all the parents of "Small Molecule" (like its grandparent, "NamedThing").  The _first_ type in the list returned by this endpoint https://smart-api.info/ui/400f7c11028ff36f460af4ea85dc72f5#/default/get_normalized_node_handler_get_normalized_nodes_get is the most specific type in the biolink hierarchy. 

Some discussion was had about adding parameters to the `NameResolution` service that allowed the user to specify the breakpoints (punctuation, spaces, exact match, inexact match, etc.).  Tickets to this effect should be created here: https://github.com/TranslatorSRI/NameResolution
