### ISSUE TITLE
Add toxicant

### ISSUE THREAD

**Issue by mellybelly** [biolink/biolink-model#119]
child of chemical substance. Q: Are all children of chemical substance role-based definitions? e.g. drug, metabolite, as siblings. Metabolite is maybe a role, but also input/output of processes.

**Comment by stuppie** [comment]
Maybe these would all be better as "has role". This is similar to ChEBI does it:
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:63952
https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=50902

**Comment by stuppie** [comment]
(IMO) A "drug" roughly corresponds to a chemical with a ["biological role"](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A24432). Not sure about metabolite, but maybe a ["biochemical role"](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A52206)?

**Comment by deepakunni3** [comment]
We should have a material entity to role association
- role is from CHEBI

**Comment by sierra-moxon** [comment]
The original issue of adding 'toxicant' in the chemical entity hierarchy is not in the model yet.  Is the intention for a chemical to be labeled with a qualifier like 'this chemical is toxic' ?  I would tend to put this as an 'association slot' (aka: edge property) that would qualify an organism to chemical association.  This issue is fairly old.   Should we tackle 'toxicity' in the chemical working group @vdancik?

**Comment by vdancik** [comment]
I agree that we should have a 'toxicant' or 'is_toxic" or just 'toxic' property. However, being toxic is concentration dependent thus we may need another (optional) property like 'toxic_concentration'.

**Comment by sierra-moxon** [comment]
proposal: because Translator doesn't set up Chemical -> Organism triples, we propose `max_tolerated_dose` as a node property on ChemicalEntity for now (with the option to add toxicant  (boolean) if we have use cases of triples between a chemical and an organism). 

https://www.cancer.gov/publications/dictionaries/cancer-terms/def/maximum-tolerated-dose
