### ISSUE TITLE
[Jena reasoner] Is the format of Biolink Model SWRL? 

### ISSUE THREAD

**Issue by 0m1n0** [biolink/biolink-model#1227]
Dear Biolink Model team,

I have recently started using  Jena to save and query biological data, and I face the ontology integration step. When I asked questions to the Jena community, some said that Biolink Model would look more like SWRL and not OWL.

Jena does not have the reasoner suitable for SWRL, however, when I coded in Java using Jena API, I got expected results with OWL reasoner. It's the same case with GraphDB server where the RDFS reasoner is used by default.

All my work is on GitHub with data and Java code: https://github.com/0m1n0/jena_reasoner
This is my first code in Java so there may be a lot of mistakes.

My questions are:
- Is the format of Biolink Model SWRL? 
- Using OWL or RDFS reasoner loses information of SWRL format? How?

Thank you for your help.
Min

**Comment by cmungall** [comment]
Hi Min,

I'll try and answer these questions but in truth you touch on some pretty major points that have nothing to do with biolink per se, but are more about debates that have raged for the last 4 decades of knowledge representation. It looks like there was a previous question perhaps on the jena mailing list, maybe you could provide a link for more context?

First, in order to try and make my answer as useful as possible, can you describe exactly what it is you're trying to do? Is there some data integration or biological question you're trying to answer? Might I ask if this is a student exercise?

Let me try and give you some specific answers and pointers for further reading.

1. Biolink is expressed in [LinkML](https://linkml.io/linkml) which is a closed-world KR formalism in the same family as frames and its modern antecedents like SHACL
2. We provide an OWL serialization for convenience (e.g. browsing the hierarchy), but OWL is an open world formalism. This means that you can't practically use OWL for checking for constraint validations in biolink, e.g. ensuring a gene has at most one name. See the caveats [here](https://linkml.io/linkml/generators/owl.html)
3. SWRL extends OWL to allow for rules, with certain limitations. There are many things that can be expressed in SWRL that can be expressed in OWL giving identical entailments for instances. For example, in your repo, entailment of inverses. You could express this with a SWRL rule but the OWL such as the one in the biolink owl will do as well (and in fact will give even more inferences in the TBox but we don't need to get into that here)
4. I'm confused by the statement "Biolink Model would look more like SWRL and not OWL", it would help to look at the source statement and the context. There are certainly some things that can be said in SWRL and not in OWL but we aren't making heavy use of these at the moment.
5. "Using OWL or RDFS reasoner loses information of SWRL format? How?". Every reasoner uses a certain formalism or profile. In you use an RDFS reason and feed it OWL axioms, it will ignore all axioms not in the RDFS subset. If you feed SWRL rules to an OWL reasoner that doesn't handle SWRL, it won't handle the SWRL. You may want to direct your question at an appropriate W3C mailing list since this doesn't really have anything to do with biolink particularly. I do appreciate that W3C documentation is pretty hard to wade through and it's not always clear how the pieces fit together.

Thank you for your interest. I think there is a lot of room for some interesting research on using biolink in combination with data and various different rule and reasoning formalisms, and if you have questions about exploring these we'd be happy to answer. I'm going to close this for now as I am not sure there is anything actionable we can do on the biolink side. But if you wanted to tag me on any discussions outside I would be happy to chime in and help provide clarification.

**Comment by 0m1n0** [comment]
Dear @cmungall 

First of all, thank you very much for your very detailed and instructive answer. Indeed, as you say, this is more of a general scientific discussion.

I sent some mails to Jena community

To clarify my situation, I just discovered the semantic world a few months ago and that is why I still lack many notions. 
I work in a small company where the goal is to better understand the microbiome world, especially biochemical reactions and pathways. The main steps I would like to achieve are the following:

1. Create our Hub linking easily public RDF data (UniProt, Rhea, GO...etc): public knowledge graph
2. Project data from biological samples such as  (meta)-transcriptomic, (meta)-genomic...etc
3. All semantic data of steps 1 and 2 are annotated and linked by Biolink Model as much as possible because I strongly trust that your 
4. Run SPARQL query (e.g. _Knowing compound A as input, give me all possible proteins, reactions, and pathways that lead to compound B as the final output_)
5. Future work: apply Machine Learning and/or Deep Learning methods on ontology to complete the knowledge (annotation) lacks

I started with GraphDB (and now discovering Apache Jena) which is very user friendly but very implicit. I wasn't paying attention to the default parameters and the choice of reasoner was one of them.
I will find out more about the links you have listed and the reasoners that can handele SWRL (Pellet?).

Once again I would like to thank you and I strongly encourage your team. Your team is very dynamic and I think I'll get back to you soon with specific biological examples for more questions and suggestions.
 
Min
