### ISSUE TITLE
Update/extend Publications model to support Publication Metadata API use cae

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#1262]
The current representation of Publications includes a Publications class and handful of arbitrary subclasses (e.g. book, serial, article) with a smattering of properties and constraints in their definitions. If recollection serves, these were created in an exploratory exercise without a concrete driving use case.  

The Translator Text Mining Knowledge Provider has provided a concrete use case that we should update the modeling to support. They are standing up a Publication Metadata API that will serve information about Publications indexed by PubMed, which they wish to make  compliant with Biolink and TRAPI specifications. The current types of information provided by this service includes the following:

- document_id (PMID, PMCID, DOI)
- pub_year
- pub_month
- pub_day
- journal_name
- journal_abbrev
- volume
- issue
- article_title
- abstract

@bill-baumgartner feel free to add to / edit this request.

**Comment by sierra-moxon** [comment]
Hi @mbrush @bill-baumgartner-  

I'm assuming we don't literally want the fields listed here, or do we?  Note the "article" subclass of "publication" in Biolink that, from the definition, appears to be the class used for PMID journal articles.  Following on from our discussion about the `publications` attribute, I imagine we'd want to make the `publication` class very broad so that many kinds of "publications" (including patents, webpages, text strings) can be typed with this category.  I imagine an `article` subclass that narrowed this very broad category into something that held all the normal metadata we'd expect to find from a PubMed journal publication would be helpful.  

Should we put up a PR and discuss this soon?
