### ISSUE TITLE
Resolver for identifiers

### ISSUE THREAD

**Issue by sooyounga** [biolink/biolink-model#1289]
**Is your feature request related to a problem? Please describe.**
I want to modify existing mappings for biolink:Gene specifically for extending `named thing` where `id` slot is concerned. OR I want to inquire how to add resolution information to identifiers.
I want to view and represent id as two separate fields of `id prefixes` and `id values`. This makes queries easier as it saves on brute transformation cost.

**Describe the solution you'd like**
Is it possible to extend `named thing` where idprefixes are added separately? e.g. if we have `ENSEMBL:ENSG00000101327` in `id`, we would have `idprefix` of `ENSEMBL` and `identifier` of `ENSG00000101327`
Or is there a better way to go about this? How should we add resolution to identifiers? Thank you

**What working group (or team) did this request originate from?**
BICAN working group from MIT SenseIn Group

**Comment by sierra-moxon** [comment]
Hi @sooyounga - we've taken another approach to working with CURIEs and local identifiers.  Instead of storing both parts independently, we use software to transform between CURIE, local identifier, and URI.  

The curies package does this quite well.  In particular, the `parse_curie` method of the `Converter` class might be helpful for your application: https://curies.readthedocs.io/en/latest/api/curies.Converter.html#curies.Converter.parse_curie 

This has some good example code: https://github.com/cthoyt/curies

```
from curies import Converter

converter = Converter.from_prefix_map({
    "CHEBI": "http://purl.obolibrary.org/obo/CHEBI_",
    "MONDO": "http://purl.obolibrary.org/obo/MONDO_",
    "GO": "http://purl.obolibrary.org/obo/GO_",
    # ... and so on
    "OBO": "http://purl.obolibrary.org/obo/",
})

>>> converter.compress("http://purl.obolibrary.org/obo/CHEBI_1")
'CHEBI:1'

>>> converter.expand("CHEBI:1")
'http://purl.obolibrary.org/obo/CHEBI_1'

>>> converter.parse_curie("CHEBI:1")
'CHEBI', '1' 

@cthoyt

**Comment by sierra-moxon** [comment]
Please feel free to close if I have answered your question; alternatively, I'll get back to this issue to close it in a few days.
