### ISSUE TITLE
additional aspect qualifiers

### ISSUE THREAD

**Issue by vdancik** [biolink/biolink-model#1415]
**Is your feature request related to a problem? Please describe.**
When ingesting Inxight:Drugs we encounter need for additional aspects

**What working group (or team) did this request originate from?**
MolePro

**Describe the solution you'd like**

| relation | aspect_qualifier |
|---|---|
| INHIBITOR OF ABSORPTION->TARGET | absorption |
|INHIBITOR OF AGGREGATION->TARGET|aggregation|
|INHIBITOR OF PROTEIN-PROTEIN INTERACTION->TARGET|interaction|
|INHIBITOR OF RELEASE->TARGET|release|
|INHIBITOR->TARGET ORGANISM|growth|

**Comment by sierra-moxon** [comment]
growth ~ inhibition

**Comment by sierra-moxon** [comment]
the only one of these enumerated values not in the PR is "growth" -- that one seems different to me because the domain/range are gene/chemical or chemical/gene, instead there is an organism in there.  

we can certainly come up with a new association that captures the relationship between chemicals and organism growth as another feature.
