### ISSUE TITLE
add mappings to some common ontologies

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#171]
So that we can determine the correct categories to use for various entities in our new knowledge graph (by programmatically consulting the biolink YAML file), it would be helpful to have mappings to these ontology classes in biolink:
+      - CHEBI:78295
+      - NCBITaxon:1
+      - PATO:0000001
+      - DOID:4
+      - NCIT:C2991
+      - HP:0000001
+      - "CHEBI:24431"
+      - UBERON:0001062
+      - MPATH:0
+      - OBO:HsapDv_0000000
+      - GMODChado:feature_relationship
+      - CHEBI:51086
+      - CHEBI:24432
+      - NBO:0000313
+      - NBO:0000243

**Comment by mbrush** [comment]
This generated the need for extending the types of mappings defined in the Biolink model.  See PR #172 and #173.

**Comment by kshefchek** [comment]
I've added some of these in https://github.com/biolink/biolink-model/pull/381

NCBITaxon:1 : mapping for organism taxon

HP:0000001: This is too broad to be a biolink class but with #381 we should have enumerated some biolink classes from HPO  (clinical course, inheritance, onset, clinical modifier), but we are missing abnormal phenotype (HP:0000118), this could be a narrow mapping for phenotypic feature.

UBERON:0001062: mapping for anatomical entity

**Comment by RichardBruskiewich** [comment]
I'm refreshing this PR  (in  https://github.com/biolink/biolink-model/pull/587),   aligning  it with more recent BIolink Model changes.  Along the way,  I'll make a running commentary here:

1. **CHEBI:78295** - I'm elaborating and updating the food model added a few months ago
2. **NCBITaxon:1** - this term  points to the  root o f NCBI Taxon,b ut no meaningful  term.  Instead of mapping this term, we simply  have `values_from:  - NCBITaxon` set accordingly in `biolink:OrganismTaxon`.
3. **PATO:0000001**  -  change accepted, but made `is_a: organism attribute` (a kind of attribute,  as suggested by Chris)
4. **DOID:4**: already mapped;  added **NCIT:C2991**, both under  `biolink:Disease`
5. **HP:0000001**  - added to exact_mappings of `biolink:DiseaseOrPhenotypicFeature`  as  suggested by mbrush
6. **CHEBI:24431** -  moved from `biolink:ChemicalSubstance` up to `biolink:MolecularEntity` 
7. **MPATH:0**  - delegated full treatment of this  mapping to PR https://github.com/biolink/biolink-model/issues/588
8. **HsapDv:0000000** -  _human  life cycle stage_ set as an instance `narrow_mappings`  to `life stage`

**Comment by RichardBruskiewich** [comment]
Covered by pull  requests  #587  and #589

**Comment by kshefchek** [comment]
I don't think HP:0000001 should map to disease or phenotypic feature, since there are subclasses that are neither (like inheritance and age of onset), and technically there are no diseases in the HPO. See https://www.ebi.ac.uk/ols/ontologies/hp

For CHEBI:24431, this is probably fine but you may want to check with @vdancik since some of the biolink definitions around chemicals are different from CHEBIs, see https://github.com/biolink/biolink-model/issues/380#issuecomment-665304828

**Comment by deepakunni3** [comment]
+1 to @kshefchek 's observation. Yes, mapping `HP:0000001` is misleading. 

More comments on the PR

**Comment by RichardBruskiewich** [comment]
> I don't think HP:0000001 should map to disease or phenotypic feature, since there are subclasses that are neither (like inheritance and age of onset), and technically there are no diseases in the HPO. See [https://www.ebi.ac.uk/ols/ontologies/](https://www.ebi.ac.uk/ols/ontologies/hp)

OK. Suggest that we remove  it. Several  other specialised HP  terms are already mapped  appropriately
