### ISSUE TITLE
need a biolink-model entity for biomarker

### ISSUE THREAD

**Issue by justaddcoffee** [biolink/biolink-model#241]
I need an biolink entity for marker, as in a biomarker/genetic marker for a disease or condition. 

I see associations for biomarkers, e.g. "has biomarker" and "biomarker for" but no entity for biomarker. 

"information content entity" or "molecular entity" are the closest things I can find in the biolink model currently...

**Comment by deepakunni3** [comment]
@justaddcoffee Since biomarker can be any molecular entity (like gene, variant, etc.), the model does not have a class for biomarker itself. Instead, we use a relation to signify that a molecular entity (like gene, variant, etc.) is a 'biomarker for' something (like disease). 

Which is why you see relations like 'has biomarker' and 'biomarker for', which can be used in the 'relation' property of an association (like [GeneHasVariantThatContributesToDiseaseAssociation](https://biolink.github.io/biolink-model/docs/GeneHasVariantThatContributesToDiseaseAssociation.html)) to signify that the subject of an association is a 'biomarker for' the object.

**Comment by justaddcoffee** [comment]
okay, thanks @deepakunni3
