### ISSUE TITLE
Implement recommendations from hackathon

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#274]
Notes:

https://docs.google.com/document/d/1FsiLLVWvPZ22n5ZGSig0ww43m60C1_PDZFu3FPbMtAo/edit#

 - [x] publication model
 - [ ] mappings
 - [ ] mapping table for predicates/relationship types

**Comment by vemonet** [comment]
I wrote an extensive example to describe the publications/evidences/experimental scores of a BioLink association.

We used Preppi (predicted protein protein interactions) as example: https://honiglab.c2b2.columbia.edu/hfpd/cgi-bin/index_jmol.cgi?view=analysis_jmol&uniprot=P03989

For one association preppi propose around 10 different scores, related to database analysis, bayesian approach, publications. So it provides a good use case for statement with multiple evidences

We did not implemented all scores, but only a few with stub values for the sake of the argument (predicted score, score from publication, final probability)

We tried to use existing concepts (mainly from prov) at the moment, but some are not perfectly clear about what they are doing. We will want to redefine most of them within the BioLink vocab for the one that are not already existing

Note that in the case of the publication I am using `bl:description` to put the excerpt at the moment.

Here is the turtle example:

[provenance_model.txt](https://github.com/biolink/biolink-model/files/3637040/provenance_model.txt)

You can browse the triples here (I loaded BioLink ontology also, note that the `explore dataset` feature will not work though):
http://into-the-prov.137.120.31.101.nip.io/describe?uri=https:%2F%2Fw3id.org%2Fdata2services%2Fdata%2Fprotein%2Finteraction%2FA1L390O14827

**Comment by cmungall** [comment]
Notes from call

pubs

 - need to add pictures taken from hackathon to docs
 - @balhoff and @cbizon will work on getting basic metadata in pub rdf graph
 - @webyrd and greg can pull in via kgx
 - need to transform x-ray json into new structure - either at x-ray end @saramsey or in kgx @deepakunni3 

predicate mapping

 - where are links to spreadsheet?

**Comment by deepakunni3** [comment]
This will help in the current discussion on provenance as part of the Data Modeling calls

**Comment by nlharris** [comment]
what is the status of this?

**Comment by sierra-moxon** [comment]
I reviewed the spreadsheet associated with this ticket and I believe the predicates in question have been modeled, and remodeled since this ticket was opened.  

we have examples/biolink3_migration/predicate_mapping.yaml as an example of mapping RO relations to their equivalent associations in biolink, we have lots of exact, narrow, broad, close, etc. mappings in biolink and we have examples of associations in the chemical->gene space (to be improved and added to as we modify predicates) in guidelines/association-examples-with-qualifiers.md (also to be expanded and improved upon as we continue to modify our predicate hierarchy).
