### ISSUE TITLE
Incorrect SKOS URI

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#280]
The Biolink model is currently using: `https://www.w3.org/TR/skos-reference/#` for the SKOS URI.  The URI should be `http://www.w3.org/2004/02/skos/core#` (See: https://www.w3.org/TR/2009/REC-skos-reference-20090818/#L1368)

**Comment by deepakunni3** [comment]
This IRI is coming from monarch-context.jsonld
Need to fix it as part of prefixcommons/biocontext

**Comment by nlharris** [comment]
So does this ticket need to be moved?

**Comment by deepakunni3** [comment]
This doesn't seem to be a biolinkml bug. This is originating from [monarch-context.jsonld](https://github.com/prefixcommons/biocontext/blob/master/registry/monarch_context.jsonld) defining `skos` with an iri `http://www.w3.org/2004/02/skos/core#`.

So the bug is originating from https://github.com/prefixcommons/biocontext/ repository.

**Comment by sierra-moxon** [comment]
one solution here, short of fixing prefixcommons, is to overwrite the skos URL in the model itself.

**Comment by sierra-moxon** [comment]
done.
