### ISSUE TITLE
biomarker

### ISSUE THREAD

**Issue by yingding1** [biolink/biolink-model#303]
Hi, I am from the biomarker team. I have the following questions:

1. when modeling biomarker, do you want us to create a separate class about biomarker and add subclass as biomarker type, biomarker function and so on. Or you want us to model a biomarker as a gene (if it is a gene) in biolink gene class, using biolink:biomarker_for as the relationship to connect this gene (e.g. biomarker) to a disease in biolink ontology?
2. The idea for the translator program is trying to stick to biolink ontology as much as possible, unless it is needed to extend the biolink ontology with new classes (such as creating a new biomarker class).

thanks
ying

**Comment by cbizon** [comment]
In slack @mellybelly says:

>Ying Ding (Biomarker Provider) i think biomarker is a context; imho the question is what are the allowable subjects and objects for the biomarker predicate
(note that biolink is not an ontology though)

So, in other words, you would do it like this:
>model a biomarker as a gene (if it is a gene) in biolink gene class, using biolink:biomarker_for as the relationship to connect this gene (e.g. biomarker) to a disease in biolink ontology?

I think this solution is right, but maybe a little inconsistent with some biolink types right now.  For instance, there are types for "drug" and "metabolite", but IMO we should drop those types in favor of the chemical_substance superclass, and use properties/relationships to say that these substances can have these roles.

Also, I agree with your statement in question 2 - the goal is to stick with, and extend where necessary, the biolink model, so that we can effectively integrate across different KPs / ARAs.

**Comment by cbizon** [comment]
@cmungall @mbrush any comments on the above?

**Comment by cmungall** [comment]
I agree

drug and metabolite are rigid subclasses of chemical_substance, rather than roles. Pragmatically this means that it's up to individual KGs whether or not a substance should be classified at the more specific level or the general. The KG merging process is a little unspecified here but I think it would take the most inclusive approach. E.g. if someone treats X as a drug, then X is a drug.

I could be persuaded that it's better in all cases to use an association to dynamically classify. I think Vlado was initially in favor of metabolite?

But the association approach is definitely better for biomarkers, since so many different classes can be biomakrers, we want to avoid combinatorial explosion, e.g. gene_biomarker, chemical_biomarker, ...

**Comment by nlharris** [comment]
So what's the action item here? Is it encapsulated in #399 meaning this issue can be closed?

**Comment by nlharris** [comment]
Is there still work to be done here?

**Comment by vdancik** [comment]
We should decide whether to model 'biomarker' as a node or an edge property (or both). In case of a node property, **molecular entity** is a natural class to have it.

**Comment by ehinderer** [comment]
Is this still being worked on?

**Comment by sierra-moxon** [comment]
biomarker_for is a relation/predicate.  
Per Chris B's comments here: 
```
So, in other words, you would do it like this:

model a biomarker as a gene (if it is a gene) in biolink gene class, using biolink:biomarker_for as the relationship to connect this gene (e.g. biomarker) to a disease in biolink ontology?
```
I think this is how folks are modeling biomarkers at the moment.  @ehinderer - do you need something more than this predicate?  Can you give me some more details about what is needed?

**Comment by nlharris** [comment]
@ehinderer did you get what you needed? Can we close this?

**Comment by ehinderer** [comment]
Yes, sorry I did not respond.
