### ISSUE TITLE
Add 'metabolite' to biolink model

### ISSUE THREAD

**Issue by vdancik** [biolink/biolink-model#35]
We should have "metabolite", in addition to "drug" as a child of "chemical substance".

**Comment by cmungall** [comment]
Do you have a use case for this? I'm a little hesitant to add this since the concept of metabolite is context dependent.

In
http://bit.ly/tr-kg-standard

We have a proposed way of allowing teams to have specific concepts while using the more minimal types. The node would be typed 'chemical substance', but you could also have a node for CHEBI:25212 (metabolite) in your graph, and connect that to you node of interest.

**Comment by vdancik** [comment]
Actually, we do have use cases that we believe necessitate :

1. Lab measurements are associated with metabolites.
2. Some diseases are caused/associated with metabolite changes (e.g. diabetes)
3. Some drugs mechanism of action is related to metabolite changes.
4. Some genes function by altering levels of metabolites.
5. Emerging field of metabolomics will likely be a valuable KS for reasoners.

Otherwise you can argue that we don't need "drug" concept either and use "chemical substance" instead.

**Comment by cmungall** [comment]
Thanks, this is very useful.

Point taken about drug. This is also a relative role; even ATP can be used as a nutriceutical, which CHEBI classifies as a drug.

For metabolite, what are some of the predicates we'd want to use?

E.g.

 * `<disease> associated-with-{inc,dec}rease of <metabolite>`
 * `<gene> regulates-levels-of-{up,down} <metabolite>`
 * ..?
