### ISSUE TITLE
be more precise re biolink:id biolink:iri biolink:name in RDF mapping

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolink-model#369]
https://biolink.github.io/biolink-model/about/mapping-rdf.html#node-and-node-properties starts off by saying that biolink:id biolink:iri biolink:name are mandatory.
But the later example shows that:
- biolink:id does not exist as a property (there's no literal "MONDO:0001083")
- biolink:iri is just the IRI of the node (not a separate property)
- biolink:name is mapped to rdfs:label

Precise the text to make this more clear

**Comment by cmungall** [comment]
I agree it could be made clearer. Do you want to make a PR with suggestions?

I think it states they are core properties of a node. This is intended as a non-normative informative statement about nodes in the biolink-model, rather than the rdf rendering.

> The biolink:id MUST be provided and MUST be a CURIE, which maps to the resource IRI/URI using a standard prefix expansion. The RDF graph MAY include the CURIE short-form represented with the predicate dcterms:identifier where the CURIE itself is a literal.

perhaps something like:

 - in the core bl model, each node must have an ID which is a CURIE [informative]
 - when mapping nodes to RDF, the node ID MUST correspond to the IRI using the [link] json-ld context [normative]

Another possibility is to specify this as a mapping to JSON-LD, where the mapping of JSON-LD to RDF (given a context) is well-defined elsewhere. cc @hsolbrig
