### ISSUE TITLE
ICD-9 or ICD9?

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#374]
Hello Biolink team,

It has been reported to me that the SRI node normalizer has `ICD-9` as a CURIE prefix, but I don't see it in the Biolink YAML file. Is this CURIE prefixe canonical?  If so, can we get it in the Biolink YAML file or `context.jsonld` file?  Because it isn't in the Biolink model YAML file, KG2 opted to use `ICD9` (following EBI OLS), so now there is a conflict. I am happy to switch but it would be helpful if all CURIEs used in the SRI node normalizer are in the `context.jsonld` file.

Thanks,
Steve

**Comment by cbizon** [comment]
Hi @saramsey you are right that the nodenormalizer is meant to only use biolink prefixes.  In the prototyping phase, the nodenormalizer was actually built off of a biolink branch rather than master, so that we could get a few extra prefixes that we needed.  The related biolink PR is this one: https://github.com/biolink/biolink-model/pull/304

You can see that the ICD-9 stuff is in there, and also in the comments that the "-" was creating some problems.  I think that we will probably drop the - and change to just "ICD9" etc.  We discussed it today, and we should be able to merge this PR today-ish, and then propagate those changes through the nodenormalization, though it will take a few more days.

**Comment by nlharris** [comment]
Looks like #304 was merged. Is there still work to do on this issue, or can it now be closed?

**Comment by deepakunni3** [comment]
Yes, the ICD prefixes have been fixed and the context.jsonld reflects the same.
