### ISSUE TITLE
Differentiate mappings according to specificity

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#418]
Differentiate mappings, according to specificity, into:
- narrow
- broad
- exact

Biolinkml now supports such modeling

Related to #185

**Comment by cbizon** [comment]
Is it helpful to have a mapping type that is something like "subclass of"?   It feels like a more specific version of one of these, but I don't know which one...

e.g. CHEBI:is_tautomer_of might be a subclass of biolink:is_similar_to

**Comment by RichardBruskiewich** [comment]
> 
> 
> Is it helpful to have a mapping type that is something like "subclass of"? It feels like a more specific version of one of these, but I don't know which one...
> 
> e.g. CHEBI:is_tautomer_of might be a subclass of biolink:is_similar_to

Hi @cbizon, in the world of semantics, I suspect that "subclass_of" is "skos:narrowMatch". @cmungall can comment here.

**Comment by cbizon** [comment]
Oh I see, I thought narrow and broad we degrees of similarity.  Like a tick might be a narrow match for a spider and an ant might be a broad match.  But looking at the skos docs, I see that you're correct.  Thanks!

**Comment by RichardBruskiewich** [comment]
I'm not really much of an expert on this but that was my general sense of the matter...

BTW, interesting example you gave... 

Biological taxonomy might drive some tagging but I'd hazard to guess that it is conditional based on what properties (features) of the organism are used for comparison

- sequence phylogeny. Q: which genes sequences are used?); 
- phenotype features. Q: are they due to "identity by descent" or "converging evolution"? what underlying genes give rise to the observed features, e.g. homeobox (HOX) genes patterns can make for hugely divergent morphology but the underlying genes may be identical but their sequence phylogeny distinct... lizards and snakes are both reptiles, but the snake has no legs... largely a consequence of HOX gene expression!); 
- geographical location; habitat; etc.

**Comment by RichardBruskiewich** [comment]
Going through a curation exercise of the biolink-model.yaml file. Sounds like we might wish to compose a more definitive set of curation guidelines for (predicate) mappings including, for example, advice relating to recording mappings of (asymmetric) inverse predicates, e.g. **biolink:gene_associated_with_condition** and wikidata:P2293 (genetic association), which have "identical" semantics except in that they are statement edge inverses of one another (with respect to domain  (subject) and range (object) directionality).  I am creating a new "[document curation guidelines](https://github.com/biolink/biolink-model/issues/426)" issue to put a post  in the ground for consideration.

**Comment by nlharris** [comment]
not sure this is actually a linkml issue.

**Comment by sierra-moxon** [comment]
exact, narrow, etc. mappings are added already throughout the model and we have subclass_of.  closing.
