### ISSUE TITLE
Split PubChem into PubChemCID and PubChemSID

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#424]
**Is your feature request related to a problem? Please describe.**
 Don't use PubChem by itself as a prefix, but rather PubChem CID or SID. 

**What working group (or team) did this request originate from?**
Data Modeling

**Describe the solution you'd like**
Need to split PubChem into PubChemCID and PubChemSID.

**Comment by deepakunni3** [comment]
Currently we have PUBCHEM.COMPOUND (PubChem CID) prefix listed for biolink:ChemicalSubstance and PUBCHEM.SUBSTANCE (Pubchem SID) prefix for biolink:Carbohydrate.

So I am assuming this issue is already been addressed. We can refine further by allowing PUBCHEM.SUBSTANCE be a valid prefix for biolink:ChemicalSubstance as well.

**Comment by nlharris** [comment]
Tagging @vdancik (not sure that worked)

**Comment by deepakunni3** [comment]
**Note:** remove `biolink:Carbohydrate`, `biolink:Drug`, `biolink:Metabolite` from the model. @deepakunni3

**Comment by vdancik** [comment]
The most appropriate PubChem prefixes to use are "CID:" and "SID:" since these are already understood by PubChem: 

[https://pubchem.ncbi.nlm.nih.gov/CID:2244](https://pubchem.ncbi.nlm.nih.gov/CID:2244)

[https://pubchem.ncbi.nlm.nih.gov/ID:2244](https://pubchem.ncbi.nlm.nih.gov/SID:2244)

**Comment by vdancik** [comment]
duplicate of #305

**Comment by nlharris** [comment]
@vdancik you're right. Should we close that one, since this ticket has more information?

**Comment by nlharris** [comment]
Vlado says this was addressed in Biolink 2.0 and can be closed.
