### ISSUE TITLE
Map EFO terms to Biolink Model

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#493]
**Is your feature request related to a problem? Please describe.**

Map EFO terms to Biolink Model.

For example,
- Map EFO term for `measurement` by creating `biolink:Measurement`
- Map EFO term for `phenotype` with `biolink:PhenotypicFeature`

**What working group (or team) did this request originate from?**

Genetics Provider/Molecular Data Provider

**Describe the solution you'd like**

Add mappings to EFO, while adding new grouping classes where applicable.

**Tag relevant members for discussion**

@RichardBruskiewich and ‪Marcin von Grotthuss

**Comment by RichardBruskiewich** [comment]
The ontology browser for EFO is at https://www.ebi.ac.uk/ols/ontologies/efo.  We can leverage the hierarchy to start mapping terms into the Biolink Model.

**Comment by RichardBruskiewich** [comment]
First, note that this issue/PR does relate a bit to the [general issue of modelling clinical data with cohorts, outcomes and exposures](https://github.com/biolink/biolink-model/pull/494). However, the focus in this issue is more on genetic associations: genetic variants associated with *something".

In assessing the overall use cases, we note that there are three levels of data/information/knowledge to consider here:

1. _disease_ (diagnoses) and/or _clinical measurements_ alongside genotyping data representing "raw" _clinical data_ in the original patient profiles of individuals.

2. aggregation and indexing of such  _clinical data_ from the first level into a _dataset_ representing at least one **cohort**, then processing such data using statistical algorithms such as "MAGMA" (and other GWAS algorithms) to assign a statistical score for the association of specific (DNA sequence) variants with specific diagnostic ("disease") status or specific qualitative or quantitative values (or value ranges) of _clinical measurements_.

3. selecting a specific score threshold from the datasets generated in level two, make "variant-to-trait" knowledge assertions where the variant is the subject concept, the trait is the object concept, and the 'predicate' is a genetic association with a qualifier score of 'confidence' of the assertion, and 'context' of the GWAS study (and underlying 'cohort study' or 'studies') which evidentially support the assertion. 

During discussions with Marcin, it was discerned that "Level 1" is buried deep inside the Genetics Knowledge Provider original "knowledge sources" and will **not** be exposed to translator. Translator will only see Level 1 and Level 2 information. More specifically, level 2 information will be in the form of GWAS analysis derived datasets generated by [algorithms such as "MAGMA"](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004219).

The remainder of this discussion here assumes that perspective.

Upon review of the list of EFO terms submitted by Marcin von Grotthuss as terms used in "knowledge" being returned by the **Translator Genetic Knowledge Provider**, we discern that some of the terms were instances of "diseases" (or disease-like) while other terms were "clinical measurements".

The "disease" EFO terms are effectively boolean "presence/absence" characteristic trait values of the cohort(s) whose disease status and genotypes were inputs to GWAS analysis.

The "clinical measurement" EFO terms are **not** referring to raw clinical values but rather, represents some qualitative or qualitative value (or range of values) of a clinical measurement treated as biological 'trait' values which, alongside cohort genotypes, were also submitted to GWAS analysis.

The output of the GWAS analyses in both cases are "variant to trait" processed GWAS genetic associations, where the specific '_subject concept_' genetic variant is associated - with some "statistical" level of confidence or "likelihood"- with a specific '_object concept_' that is specifically that represents a given disease status or biological 'trait' value.

In both cases, there is an implied (level 2 information) 'cohort' lurking as the source of the value, hence, the 'context' of validity of the value. In that sense, such a cohort (or rather, its study?) is the source of **evidence/provenance** lurking behind the genetic association, which itself is exported by the KP as a (level 3) knowledge assertion (knowledge graph edge).

In practical terms, each 'object concept' disease in the resulting Biolink Model compliant knowledge assertion is a specific 'disease' category node (the specific disease identified by EFO 'disease' term) or a 'trait value' category node.   However, we do not (yet) have a category called 'trait value' so rather, the current decision is to use suitably qualified instances of the concept category of 'phenotypic feature' as the proxy concept class for 'biological trait'.  

By '_suitably qualified_' we mean that in addition to using the specific EFO term associated with the given clinical measurement of the genetic association, we may also need to add a suitable node property to constrain the concept node to some particular quantitive or qualitative trait clinical measurement value.

The association itself will document the GWAS score of the association, as a measure of confidence of the genetic assocation itself.

We will strive to clean up the [Biolink Model Pull Request 497](https://github.com/biolink/biolink-model/pull/497) to simply reflect and support the above understanding of the Genetics Knowledge Provider use cases using EFO.

Note that although the PR will include a Biolink Model patch to support the initial comment by @deepakunni3 above, namely 

```Map EFO term for measurement by creating biolink:Measurement```

 and 

```Map EFO term for phenotype with biolink:PhenotypicFeature```,

in fact, the modifications required to support the above Genetics Provider use case does **_not_** rely on these specific changes to the Biolink Model. Rather, the use cases rely specifically on the assignment of EFO as a `id_prefixes` namespace to `disease` and `phenotypic feature` categories, plus a clarification of the appropriate `association` class including applying constraints on _object concept_ nodes relating to `PhenotypicFeature` qualifying trait values.

**Comment by RichardBruskiewich** [comment]
Merged this issue and the associated PR (#497) to issue https://github.com/biolink/biolink-model/pull/494 for a coordinated treatement of clinical data modelling.
