### ISSUE TITLE
Add additional description property values  to Biolink Model  classes as required to better inform  the user of the model

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#525]
Several Biolink  Model  classes  (perhaps, slots,  types and mixins as well) could use  better `description` properties

**Comment by nlharris** [comment]
sounds useful, is this something you could do?

**Comment by nlharris** [comment]
@RichardBruskiewich please assign yourself if this is something you could work on. Thanks!

**Comment by sierra-moxon** [comment]
This is definitely a worthwhile pursuit and critically important to the interpretability of the model, however, I'm going to close this issue as "in progress, forever" :) We always will want better and more refined examples, descriptions, and mappings in the model.  It's an ongoing process and any time we change something in Biolink, we should also review and refine our definitions.  I did keep open specific instances that need better documentation (and perhaps some remodeling) like #502 which asks us to better annotate the "attribute" class and organize a mixin so that "has_attribute" can be applied at the NamedThing and Association levels.
