### ISSUE TITLE
WormBase prefix expansion

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#530]
Biolink has this expansion for Wormbase:

```
"WormBase": "https://www.wormbase.org/get?name=",
```

GO is using `http://identifiers.org/wormbase/` in the NEO ontology (and so in GO-CAMs). It would be good to align these. @cmungall which is preferred?

**Comment by RichardBruskiewich** [comment]
Actually, the currently registered URI from _identifiers.org_ for _wormbase_ is:   `https://identifiers.org/wb/`.

This resolves properly to the wormbase site, e.g. try https://identifiers.org/wb/WBGene00000001 whereas the GO version http://identifiers.org/wormbase/WBGene00000001 doesn't work (anymore.. perhaps it did years ago?). 

The current version in the Biolink Model _context.jsonld_ (https://www.wormbase.org/get?name=WBGene00000001) also appears to resolve but seems to originate from one of the `default_curi_maps` since it is not listed under the model yaml `prefixes` section.

**Comment by RichardBruskiewich** [comment]
I'm going to set the wormbase: prefix to the identifiers.org resolved URI, https://identifiers.org/wb/, OK. We don't have much influence over what other external resources are using (e.g. GO). Somebody else will need to poke them to update their prefix to URI mapping.

**Comment by RichardBruskiewich** [comment]
> 
> none of the URIs we use should ever have '?'s or query parameters in them!

Yep. Totally agree @cmungall and @balhoff. However, since the Monarch PrefixCommons entry for WormBase had that deficiency, note that I've posted a PR request to fix the URI to the Identifiers.org version (see PR https://github.com/prefixcommons/biocontext/pull/32).

**Comment by kshefchek** [comment]
My understanding is the default_curi_maps section of the biolink model worked as a priority list, so the idot_context overrides the monarch context file, is this not the behavior we're seeing?

**Comment by deepakunni3** [comment]
@kshefchek Thanks for pointing that out. I wonder how the ordering is. Perhaps the idot_context gets overridden by monarch context. 

Will have to look at how biolinkml parses the `default_curi_maps` directive

**Comment by cmungall** [comment]
order should be order of priority

what sometimes happens is that we end up with 2 entries rather than a
de-dedupe, e.g. if different case is used (this is a prefixcommons bug,
clobbering should be case insensitive), or a different prefix. Ideally we'd
have warnings (e.g. "prefixes include FB and FlyBase but these are the same
resource")

**Comment by RichardBruskiewich** [comment]
I certainly stirred a tempest in a teapot here!

I issued the _correct_ PR at https://github.com/monarch-initiative/dipper/pull/1000
I cancelled the PR at https://github.com/prefixcommons/biocontext/pull/32
I removed the WormBase prefix under `prefixes` of the Biolink YAML in this *master* commit: https://github.com/biolink/biolink-model/commit/a525c535018e13985e85413ad4e335ca5de2dea7
