### ISSUE TITLE
Why not identifiers?

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#60]
My understanding is that the BLM will not have URI or curie style identifiers for its elements.  Can somebody explain why?  The advantage of having identifiers in my mind is that we're no longer stuck with particular labels.  If we decide that "molecular activity" should be called "molecular function" to bring it in line with GO, then we can do that with impunity because the identifier would not change.

Note that I am not suggesting that the BLM has to have all BLM:00001 type identifiers.  I think it would be entirely reasonable to use identifiers from other systems (like RO or SIO or whatever is appropriate for a given identity but choosing a single best identifier for each concept).

**Comment by cmungall** [comment]
It's a good question, and I am typically the proponent of IDs/CURIEs.

I think your proposal is actually in line with what is intended. The thinking was the BLM was more like a schema than an ontology, with the elements mapped to identifiers. We didn't want to prioritize any one collection of ontologies. One thing we can certainly do is change this and always have a canonical ID/URI for every element.

Beyond that, what should change? Should we have the neo4j:labels (what is called category here, I hate that they chose 'label' for this) be IDs/CURIEs/URIs? I hate to be driven by database-specific issues but that would end up looking pretty terrible for browsing the data, and this is an important use case in the short term. So the alternative is to standardize on the human-readable names here (at least in the short term, which is important for our project, I'd like to explore ways to make everything more robust longer term).

Also, the intent is that groups can use detailed typing in their own KG using type links between nodes and ontology classes (where those nodes would be like other nodes, and have id/uri/name), but I'm not sure how many other groups are doing this.

**Comment by cbizon** [comment]
Yeah, I get not wanting to prioritize a particular ontology.   But FWIW, having a canonical URI/ID for each element seems important to me.  We're going to do it internal to ROBOKOP, so I'd rather that we were doing it uniformly.

You raise a good point about neo4j lables though.  We are using names for the "Label" (agreed how bad that is, but we're using an identifier for "Type" (another neo4j name I don't like).    I guess I'd like to move to identifiers for both.  I don't anticipate a lot of interactive use of the neo4j so I'm ok with that (but maybe I'm wrong).

**Comment by jmcmurry** [comment]
I don't feel super strongly, but IDs smell better to me. 
I would, however, advise against BLM, whether as an acronym or a prefix. BLM is already widely known and understood as "black lives matter"; not that these are overlapping contexts, but nevertheless, I think the prefix should just be 'biolink'. Short sweet and immediately recognizable.

**Comment by cmungall** [comment]
good points all!

**Comment by RichardBruskiewich** [comment]
I love this Translator prototype express train... 

I hope we can nail these standards to the ground sometime soon since it is very hard to code against a moving target!

1) on the BLM versus biolink prefix - I guess data from Monarch itself should not be tagged as "biolink" perhaps and that rather, 'biolink' be reserved for Biolink meta data ?

2) I generally agree with Chris B. - it would be good to have proper globally resolved id's for the biolink entries - URI and CURIE - even if the user uses the (model unique) term labels / names in their work and tagging of data.

3) the Biolink model suggests CapitalizedCamelCase for concept types, thus:

   "http://bioentity.io/vocab/NamedThing" and "biolink:NamedThing"

but snake_case for predicates. I'm ok with that but how does this translate into a predicate CURIE?

   "http://bioentity.io/vocab/treats_condition" and  "biolink:treats_condition" 

or is the object id still "TreatsCondition", namely 

   http://bioentity.io/vocab/TreatsCondition and "biolink:TreatsCondition" ?

**Comment by cbizon** [comment]
Note that there are identifiers - they're derived from the yaml file and the appear in the json-ld context file.
