### ISSUE TITLE
Document the best practices for treating certain links/relationships as node/association slots

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#605]
Document the best practices for treating certain links/relationships as node/association slots.

Related to https://github.com/biolink/biolink-model/pull/587 and https://github.com/biolink/biolink-model/pull/582

**Comment by sierra-moxon** [comment]
This is subsumed in work the predicates WG is doing - we'll establish some rules for what semantics are stored in the predicate, qualifier/modifier and node properties.  The rules will be fairly broad but look something like this:

- Predicates should explain “what” you know.
- Provenance (with evidence) should report “why” you know it.
- Qualifiers should refine what you know except in a limited set of modifiers that is agreed upon in advance (ie: negation, probability, predicated, potentially -- 'epistemic qualifier enumeration' potentially fits in this exception).
-- More specifically, the core triple (subject+predicate+object) should be true, even without qualifiers (always assume a “some : some” interpretation of a ‘core triple’ - ie: some subject is ‘related to’ some object via predicate, except in cases above).
- The definition of a new predicate should specify why it’s different from its parent and why it can not be synonymous with its parent.
- Translator specific rules:
--Subjects and objects (nodes) should be basic (ie: chemical instead of exposure to chemical).
-- For now, lean towards the ability to find knowledge in “one hop.”
-- Try to reuse predicates and qualifiers and associations if we can.
