### ISSUE TITLE
Mappings for monarch to biolink model

### ISSUE THREAD

**Issue by lhannest** [biolink/biolink-model#62]
@cmungall There are categories in Monarch (https://biolink-kb.ncats.io/types) that aren't in the biolink model, for example "variant" and "phenotype".

How should these be handled?

**Comment by mbrush** [comment]
These are in the blm but by slightly different names:

variant = sequence variant ([link](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L1208))

phenotype = phenpotypic feature ([link](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L831))

**Comment by mbrush** [comment]
As an aside, I note that there is no 'allele' type in the BLM - whereas there were separate 'allele' and 'sequence variant' types in the initial iteration of the semantic types list.  I actually think this is a good idea - as having both is likely to cause confusion  and inconsistent annotation.  But I wonder if the one we keep should be 'allele' rather than 'sequence variant'. 

'Sequence variant' is defined as _"an allele that varies in its sequence from what is considered the reference allele at that locus"_.  This definition is based on a **_role_** played by an allele in a particular context of analysis/evaluation.  A given allele may be reference in one context/association, and variant in another. Furthermore, this excludes alleles considered to be 'references' - precluding us from describing things like WT alleles.

Seems like the more foundation type to keep would be 'allele', instead of 'sequence variant'.  We could additionally capture 'variant allele' and 'reference allele' under this concept, if there are use cases for capturing the fact that the allele was considered variant (vs reference) in the context of a particular association.  But if there is this could be modeled in a different way (e.g. the oban:association_subject_property)

@cmungall curious about your thoughts here.

**Comment by lhannest** [comment]
Thanks @mbrush, there's one more: `model`, should it map onto `model to disease mixin`? I'll have the biolink beacon rename these categories as such.

**Comment by cmungall** [comment]
@mbrush - for variants, can you make a separate ticket? This goes beyond aligning with monarch - e.g. VMC, you and I will work with @deepakunni3 on this

@lhannest - the mixins should not be used directly. but model is an interesting case, it is more the role the entity plays in the relationship

**Comment by kshefchek** [comment]
See https://github.com/monarch-initiative/dipper/pull/746 for the monarch implementation

I can also take a look to see if there are any categories missing from biolink-model from our legacy categories: https://github.com/monarch-initiative/scigraph-docker/blob/master/conf/monarch-load-global.yaml#L1

At a quick glance things missing are:
- inheritance
- clinical course
- reagent targeted gene
- snv
- phenotypic_marker (not sure where we use this)
- quality
