### ISSUE TITLE
Implement Translator Feature Variable Ontology [was: Incorporate work from clinical WG]

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#636]
See notes [here](https://docs.google.com/document/d/1M5jT-JDGRxQnFvuFZjWnhbJGYWTBu8zo7lDP6AW9g0k/edit)

(Will create more granular tickets soon)

**Comment by sierra-moxon** [comment]
- Clinical Working group agreed that an ontology could be created from feature variables.

**Comment by sierra-moxon** [comment]
- @vdancik presented progress on the data modeling call on March 4 - continuing discussions with feedback from DM team.

**Comment by nlharris** [comment]
This issue seems too vague to be useful -- maybe @karafecho can add details, or maybe we can just close it?

**Comment by karafecho** [comment]
Clinical feature variables often do not map precisely to existing ontologies. For instance, in electronic health records, a medication is not a drug or chemical, it's a prescription and/or administration of a drug. Outcomes such as ED visits for respiratory issues also are tricky. To overcome these challenges, the Biolink team proposed the following solution: a "Translator Feature Variable Ontology (TFVO)". The TFVO would support the ability to newly mint CURIES for feature variables that do not map precisely to existing ontologies. The Clinical Data Committee is now conducting requirements gathering in order to move this effort along.

**Comment by karafecho** [comment]
This is one of several issues related to the Clinical Data Committee. You can probably rename this "Implement Translator Feature Variable Ontology".

**Comment by nlharris** [comment]
Thanks. Can I assign it to you?

**Comment by karafecho** [comment]
I guess so, although the SRI and Biolink team will be the ones implementing the new service.

**Comment by sierra-moxon** [comment]
replaced by: https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/12
