### ISSUE TITLE
non-existent BFO terms?

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#696]
I can't find evidence of these two terms in BFO or RO:

https://github.com/biolink/biolink-model/blob/ff0369c948fb677006ce8c2f21ab0f8cd9c43ad6/biolink-model.yaml#L1055-L1056

**Comment by sierra-moxon** [comment]
We talked about this issue in the helpdesk today.  We can't find evidence of these terms in the BFO either (though we are not sure why they weren't obsoleted instead of just removed.  For example, we can find references to these terms in other ontologies so they must've existed at some point.   Removed them from the model nonetheless.
