### ISSUE TITLE
versioning for the KG standard for the Translator project

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#87]
I'd like to propose that we adopt an explicit versioning scheme for the Translator KG standard. Ideally, it should be clearly labeled on the standard document, and incremented when there is agreement that a new release should be ratified. Release notes documenting new changes should be added for each release.  See SBML standards process for an example:  http://www.sbml.org.

**Comment by cmungall** [comment]
Yes, the current situation is far from ideal.

Currently we use the GH release mechanism, which releases everything in the repo

Releases here
https://github.com/biolink/biolink-model/releases

Releases automagically get made to zenodo too, thanks to the wonders of zenodo/gh integration. See the badge at the top of the README: https://zenodo.org/badge/latestdoi/112995625

E.g.
https://github.com/biolink/biolink-model/releases/tag/v1.1.0
or alternatively:
http://dx.doi.org/10.5281/zenodo.1242671

The repo can be browsed at this state, e.g
https://github.com/biolink/biolink-model/tree/v1.1.0

The problem here is there is a lot of generated artefacts in the repo that are not of immediate interest to every Translator person

You can navigate to the yaml file, for a release e.g
https://github.com/biolink/biolink-model/blob/v1.1.0/biolink-model.yaml

Or to the generated markdown
https://github.com/biolink/biolink-model/blob/v1.1.0/docs/index.md

What you don't get is the nicer github pages view; this URL always points to master:
https://biolink.github.io/biolink-model/docs/

Open to better ways of doing this, but I'd maybe like to separate two discussions:

 1. the mechanics of how this is done (e.g. should we make one uber versioned document rather than one page per datamodel element; should we have github pages for each of the versioned releases)
 2. the release process and governance

Number 2 is probably a big one. We have not been operating like a normal standards body as we don't have years to deliberate, we're iterating fast and hopefully not ruffling too many feathers along the way. As things settle down we should change this. This would be a good thing to discuss F2F next week

**Comment by sierra-moxon** [comment]
@saramsey - do you think this is a biolink-model issue or an SRI issue or a translator-wide issue?  I think for biolink-model we follow semantic versioning.  Please feel free to reopen if necessary for SRI to work on versioning across translator? :)
