### ISSUE TITLE
add a mixin predicate to test removing subclassOf from the relatedTo predicate hierarchy

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#883]
<img width="1244" alt="Screen Shot 2021-10-01 at 8 54 58 AM" src="https://user-images.githubusercontent.com/4561292/135650859-8cbaadd3-5267-4a9f-8129-4251b9a352f6.png">

https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/D.6_metformin-ferritin.json

From workflow B, we're returning data in two-hop queries that walks up the 'parent' (subclassOf) hierarchy to a high-level protein term ('eukaryotic protein'), then back down to the requested protein term (as a child of that high level protein term).  The subclassOf path walking causes what seem to be noisy results in answering the query.  

Discussion today at the tools helpdesk meeting (part of the relay), asked if we could make a mixin that would include every predicate under relatedTo, except subclassOf, to test how moving subclassOf out of relatedTo hierarchy would help solve this problem.  The mixin would be in addition to keeping subclassOf in the relatedTo hierarchy, and used to avoid this problem but not make a breaking change to the top layer of the predicate ontology.

Another suggestion was to call this new mixin "associated with" for the name of this predicate mixin.

tagging @vdancik @andrewsu @cbizon

**Comment by cmungall** [comment]
An over-arching concern here is that we may not have consensus on modeling of "grouping" objects:

 * gene families and ortholog groups
 * chemical entity groupings
     - e.g. charge/symmetry neutral groupings
     - high level groupings such as "amino acid"
 * named pathways and pathway groups and GO BP terms
 * disease "entities" and disease "groupings"
 * organisms and species and taxa

Broadly speaking there are two modeling patterns:

* Class-style: everything is a class, and subClassOf is used to relate things
* Entity-style: clear separation between discrete entities and their groupings, with a non-subClassOf predicate

My sense is that there is varying degrees of comfort for each style dependent on the category being modeled. E.g. people are more comfortable with Class-style for diseases but others like @vdancik are definitely more comfortable with Entity-style for chemical entities. People coming from an OBO background are more inclined to think of everything as a class. Something like proteins is inbetween cc @mikebada.

We need to reach some resolution here (DM call cc @nlharris)

This has direct bearing on this question, as it will affect precision and recall.

One disadvantage of using Class-style ubiquitiously is that it gives us less of a lever to control precision/recall. subClassOf logically holds equally for the relationship between a chemical entity like L-cysteine and cystein as it does between L-cysteine and "chemical entity". Similarly, with class style, all these are true:

 * Human-FOO-1 subClassOf Human-FOO subClassOf FOO subClassOf protein subClassOf material entity subClassOf thing

Perhaps stated more concisely

 * **With class-style, any two nodes are two hops away, as everything is a subClassOf Thing**

We can attempt to address this with something like a directSubClassOf, but this is doesn't work for reasons I won't go into here

I am very supportive of more levers to control precision/recall in queries. I am neutral as to whether

 1. we remove subClassOf from related_to and introduce a new broader grouping
 2. we introduce a new grouping below related_to that excludes sub/superclass of

I think this decision needs to be made by the consortium as I don't know what will break for people

I have a strong terminological preference for 2, because I find it unintuitive to say that fanconi-A is unrelated to fanconi

But either way, we should understand as a group that any such filtering may throw out things such as the relationship between a protein isoform and a protein with class-style modeling. I feel entity-style is more appropriate for translator.

**Comment by nlharris** [comment]
Added to agenda for next DM call
