### ISSUE TITLE
move the knowledge_source slot to Entity class in favor of the provided_by slot

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#938]
In keeping consistent with the deprecation of provided_by, replace its occurrence in classes with knowledge_source slot.

**Comment by mbrush** [comment]
Per discussion on 1-13-22 Data Modeling call . . . .the original [provided_by](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L6086) property in Biolink was explicitly defined as an association slot / edge property.  It was deprecated recently in favor of the more granular set of 'knowledge_source' edge properties.  The issue here is that provided_by  was included (accidentally?) as an allowable slot in the 'entity' class (see [here](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L6555)).  And some KGs are using provided_by on nodes to capture node 'provenance'.   

If we want to support a property to capture 'node provenance', we need to first determine what we mean by 'node provenance'.  Is it the source that defined the concept represented by the node IRI?  Is it the source that created/minted the IRI itself?  Is it the resource from which the data containing the node was retrieved (which will often be different than the source of the IRI itself, e.g. CL may be the source of an IRI for a node representing particular cell type, but the data holding this node may have been retrieved from a KB like ArrayExpress)?

We should review usage of provided_by in existing KGs to understand how it is being used (i.e. this of the semantics above apply) . . . and then we can decide if and how we need to support this use case.  e.g. we may want to define separate node properties (who defined a concept/IRI (e.g. 'defined_by'), and where it was retrieved from (e.g. 'retrieved_from'). Or we may decide to re-use the edge property 'knowlege_source' by allowing it to apply to nodes as well as edges. 

See [ticket 801](https://github.com/biolink/biolink-model/issues/801#issuecomment-921157984) for more.
